export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";

export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";

export const GET_PLAYER_SUCCESS = "GET_PLAYER_SUCCESS";

export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";

export const EDIT_PLAYER_SUCCESS = "EDIT_PLAYER_SUCCESS";
export const EDIT_PLAYER_FAIL = "EDIT_PLAYER_FAIL";


